
---
# local
spring:
  profiles: local
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---

spring:
  profiles: dev
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

---

spring:
  profiles: release